# Generated by Django 5.0 on 2024-03-02 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('important_things', models.TextField(blank=True, null=True)),
                ('libraries', models.TextField(blank=True, null=True)),
                ('frameworks', models.TextField(blank=True, null=True)),
                ('tools', models.TextField(blank=True, null=True)),
                ('best_practices', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('examples', models.TextField(blank=True, null=True)),
                ('implementation_instructions', models.TextField(blank=True, null=True)),
                ('installation_guidelines', models.TextField(blank=True, null=True)),
                ('settings', models.TextField(blank=True, null=True)),
                ('things_to_avoid', models.TextField(blank=True, null=True)),
                ('follow', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('top_keywords', models.TextField(blank=True, null=True)),
                ('textrank_keywords', models.TextField(blank=True, null=True)),
                ('named_entities_subject', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
