# Generated by Django 5.0 on 2024-03-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='named_entities_subject',
        ),
    ]
